### ISSUE TITLE
Don't know how to use the multiple lines you suggest

### ISSUE THREAD

**Issue by leninberg** [stoyanovgeorge/ffmpeg#1]
Hi there!

```
ffmpeg -i input.mkv \
    -map 0:0 -map 0:1 -map 0:1 -map 0:3 \
    -c:v copy \
    -c:a:0 libmp3lame -b:a:0 128k \
    -c:a:1 libfaac -b:a:1 96k \
    -c:s copy \
    output.mkv
```

Should all this be put inside a script file (bat file)?
If I paste it in the shell (windows) I get errors, one error per line

Thank you

**Comment by stoyanovgeorge** [comment]
Hi Leninberg, the idea of this is to make it easily readable and not to scroll left and right in order to see the code. This code works perfectly well under Linux, for Windows I think you have to replace `\` with `^` so your code has to be: 
```
ffmpeg -i input.mkv ^
    -map 0:0 -map 0:1 -map 0:1 -map 0:3 ^
    -c:v copy ^
    -c:a:0 libmp3lame -b:a:0 128k ^
    -c:a:1 libfaac -b:a:1 96k ^
    -c:s copy ^
    output.mkv
```

Please try it and let me know if that works.

**Comment by leninberg** [comment]
Thanks! That did it! Cheers!
