### ISSUE TITLE
script failed

### ISSUE THREAD

**Issue by ke4obt** [stoyanovgeorge/ffmpeg#2]
I downloaded your script and tried to install it on a fresh, new install of Ubuntu server 18.04 64-bit. 
It gives me this error: ERROR: x265 not found using pkg-config - and tells me to "Include the log file "ffbuild/config.log" produced by configure as this will help solve the problem.", but I can't find that config.log or ffbuild anywhere.
I tried the automated script and got the same errors.
It never came up with the "reboot" option/command. It just ends with that error, how to report it on the mailing list/IRC then asks if you want to remove the install directory.
Is there something I've done wrong?
I am a visually impaired user and I'm trying to install this on a Dell PowerEdge server.

Thanks in advance,
Flip

**Comment by stoyanovgeorge** [comment]
I am sorry for the late reply on your issue, I have just saw your ticket. If you don't need the h.265 support you can just comment the line in the compilation [script](https://github.com/stoyanovgeorge/ffmpeg/blob/master/compilation.sh): `# sh $PWD/scripts/libx265.sh 2> $HOME/ffmpeg/logs/libx265.log` I guess they have changed something in the compilation file of the x265 and some of the compilation requirements are unmet. I will check it and fix it over the weekend.

**Comment by AdsonCicilioti** [comment]
Any news about this?

**Comment by stoyanovgeorge** [comment]
did you try to comment the line for compiling the libx265 library. I think most of the people don't need support for this video codec.

**Comment by stoyanovgeorge** [comment]
I have finally updated the compilation script and now it should work just fine on Ubuntu 18.04. I have also updated the version of the ffmpeg it compiles to 4.1. I am closing the issue.
