### ISSUE TITLE
Decklink support?

### ISSUE THREAD

**Issue by alatteri** [stoyanovgeorge/ffmpeg#3]
Would it be possible for you to include compilation support for Blackmagic Decklink SDK.

Thanks.

**Comment by stoyanovgeorge** [comment]
@alatteri,first you need to install the Blackmagick Decklink SDK, which I don't have access to and then you need to compile FFmpeg with `--enable-decklink`, just add this line to the `ffmpeg/scripts/ffmpeg.sh` script and run compilation.sh script in the main directory. If you do not want some of the installed packages, feel free to remove them from the `ffmpeg.sh`.

**Comment by stoyanovgeorge** [comment]
You can check this link how to compile it from source: [decklink compilation instructions](https://gist.github.com/afriza/879fed4ede539a5a6501e0f046f71463)
